export interface IPostAction {
  type: Action;
  payload?: any;
}

export enum Action {
  GET_TAGS = "GET_TAGS",
  GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS",
  GET_TAGS_ERROR = "GET_TAGS_ERROR",
  SHOW_TAGS_FILTERED = "SHOW_TAGS_FILTERED",
  HIDE_TAGS_FILTERED = "HIDE_TAGS_FILTERED",
  SELECT_TAGS_BEGIN = "SELECT_TAGS_BEGIN",
  SELECTED_TAGS = "SELECTED_TAGS",
  REMOVE_SELECTED_TAG = "REMOVE_SELECTED_TAG",
  GET_IMAGES_IN_DISK = "GET_IMAGES_IN_DISK",
  GET_THUMBNAIL_IN_DISK = "GET_THUMBNAIL_IN_DISK",
  REMOVE_IMAGES = "REMOVE_IMAGES",
  LOADING_START = "LOADING_START",
  LOADING_END = "LOADING_END",
  RESET_STATE = "RESET_STATE",
}
